export const Maahmaahyo = [
    "Aadmi la aragyaaba, dhib la arag",
"Aan wada hadalno waa aan heshiino",
"Aar qoyey dacawo la mood",
"Abaal dad galaa badan, dad guda,ase yar",
"Abaal raaga rag baa leh, mid baaqdana haween baa leh, mid soo dhakhsadana xoolaa leh",
"Abeesada taan sanqarta iyo tan aammusan, tan aamusan baa la qaatay",
"Abeesana dhul u eki bay wax ku dishaa, waadaadna dad u eki",
"Abkeey dooli diloow, dad nool maas u daahaa",
"Aboorku inta aanu kugu tufin ayaa lagu tufaa",
"Abuur iyo waano, abuur baa horreysey",
"Adduun i khatal",
"Adduunyo ka kabo li’id, aakhirana u salaad li’id",
"Adhi been wuu didaa beense ma dhutiyo",
"Adhi jiri ma kala abaal waydo",
"Adhi jiri xil bay wadaagtaa",
"Adhi magantii ma barriiyo",
"Adhi shidho laga daayo",
"Adin waa la dhibaa, ilna waa la dhawraa",
"Adoo nabad u balawaara, beloy kaalay lama yari",
"Aduun wey kii amoodeey ogaaw",
"Af aamusani marti ma sedo",
"Af aanad aqooni aabahaa wasna waa kaa yeedhsiiyaa",
"Af aanad lahayn ileen aamus lama dhaho",
"Af aanad lahayn lama qabto",
"Af ama reer aw mahdi ha ku hadlo ama lo’ ha kuu daaqdo",
"Af Daboolan, Dahab waaye",
"Af hadlaaba aamus",
"Af jabtay sideedii ma noqoto",
"Af jooga looma adeego",
"Af macaan gacan macaan baa dhaanta",
"Af nooli waa hadlaa Eyna waa ciyaa",
"Af noolina waa hadlaa eyna waa ciyaa",
"Af waa kane, maxaa lagu aamaa",
"Af wax cunay xishoo",
"Afar gacmood abaar ka daran (Hunguri weyni waa cudur)",
"Afar layskuma daro: Waan guuri; Waan guursan; Geel baan qaadi; Geenyaan gadan",
"Afar waa afar: Noloshu waa Niyad; Naftu waa qaali; Nacaybku waa olol; Nabsigu waa qaraar",
"Af-ka nool abooto mudac",
"Afkaad goojaamo kaga keentay kula hadal",
"Afkaagoo ku xidha oon ku furin alle goo baa la yidhaahdaa",
"Afkii dab yiri ma guban",
"Afxumo nabad way kaa kaxaysaa colaadna waxba kaagama tarto",
"Ag-joog, Ninkii xilo doonayowna Xamaro agjoog",
"Alif kaa xumaaday Albaqra kaama haro",
"Alla aamin ma iisho",
"Alle watow wehel uma baahna",
"Allow aqoon xumo hannagu caabin eexona hannooga tegin",
"Allow nin aan wax ogeyn ha cadaabin",
"Ama afeef hore lahow ama adkaysi danbe",
"Ama faro dufan leh ku qaad ama faro dac leh",
"Ama waa la muuqdaa ama waa la maqanyahay",
"Ammaan lama dhu-dhumiyo",
"Ammaano cirkaa diiday, oo dhulkaa diiday, oo Aadmi baa qaatay",
"Ammaano kugu raagtey inaad leedahay baad mooddaa",
"Amxaar la arag yaaba ferenji xaaji",
"Amxaaro madax gumac galay leedahaye madax hadal galo ma laha",
"Aqal libaax lafo lagama waayo",
"Aqoon la’aani waa iftiin la’aan",
"Aqoon xumo abaar ka daran(qorsho xumo abaar ka daran)",
"Arin nin la toosan ayaa nin kale tuur la leh",
"Aroos lagama raago, lagumana raago",
"Arrad waa dan uskagse waa doqonniino",
"Arrimo rag waa mudacyo afkood",
"Arrin aan sidii futo riyaad la feydin, ma fayoobaato",
"Arrin kaa tagtat Ahaa sooma celiso",
"Arrin waa mid kugu soo booddiyo, mid kugu bariday",
"Arrin xumo abaar ka daran",
"Atoorku intiisuu guun ku yahay",
"Awr awr wado iyo nin naagi waddi midna kaama leexdaan",
"Awr kala guurtay uurar kala guurey baa ka xun",
"Awrba awrka ka horreeya ayuu horraan-qaadkiisa leeyahay",
"Awrka danbe awrka hore socodkiisuu leeyahay",
"Ayax teg eedna reeb",
"Ayaydaa taag darran iyadoon tabar lahayn bay dadka isku taagtaagi",
///////////////////////// 75 line above

"Baadi nimaan lahayn bay ag joogtaa",
"Baahiyi qof kuu daran bay kuu geysaa",
"Baareey guur, oo sixnigaagana la guur",
"Baddu waa isku dhadhan",
"Badhi mag ma laha",
"Balaayo laba qad ma leh",
"Balaayo madax la qabtay leedahaye minjo la qabto ma laha",
"Balaayo buulkaagaa laga galaa",
"Ballan habeenimo, jarmaado subax buu leeyahay",
"Ballaysin bir ka adag",
"Ban waraabiyo gaala baqataba baraa la helaa",
"Bannaankaba arkaayow maxaa babac ku saaraaya",
"Bannaankiis mare maradiisa geed ma qabsado",
"Baqal fardo la miratay dhigood bay is moodaa",
"Barasho horteed dad ha nicin",
"Barasho horteed ha i nicin",
"Barasho u yeelo geedkaad cugsan doonto",
"Bari waaga mooyee wax san kama yimaadaan",
"Barrooriba buulkeeday ku hartaa",
"Bartii yaqaan, bari uma korodho",
"Bartii yaqaan bar xoolaad kuma korodho",
"Baruur qudhuntay baa baruuro qudhmisa",
"Baruuro sabool, badhaadhaa leh",
"Baryo badan iyo bukaan badanba waa laysku nacaa",
"Baryo iyo is daluuc layskuma daro",
"Basari buulkeeda bayaayo waaye",
"Baso waa baso si kastoo loo subko",
"Bawdo rag, maalinba midbaa qaawan",
"Baayac-mushtar bilowgiis bur iyo bajiye waaye",
"Been doode been buu dhaartaa",
"Been fakatay runi ma gaadho",
"Beeni raad ma leh",
"Beentaada hore runtaada danbay u xuntahay",
"Beentaada hore, runtaada dambey dishaa",
"Beentaada hore, runtaada danbey u daran tahay",
"Beer wax dhalow ba’",
"Beerka jecli, xaydha jecli",
"Belaayo aanad guriga keensan banana kaama raacdo",
"Belaayo guur bay ku tiraahdaa ama guurso",
"Belaayo hor la qabtay leedahay ee dabo la qabto ma leh",
"Belaayo kaa sii jeeda layskuma soo jeedsho",
"Belo markay adiga kaa maqan tahay, qayrkaa bay ku maqan tahay",
"Bidaari sibiq bay kugu gashaa",
"Bilaysini Bir ka adag",
"Bililiqo doon waa nabad diid",
"Bil-saddex reerkaagana waa kaa kaxaysaa, reer kalena kuuma geyso",
"Bir baa bir goysa",
"Birta adag dab ayaa lagu jilciyaa",
"Bisayl iyo ceedhiin waxa u dhexeeya waa yac-yacood",
"Bisqin rag bay kuu gaysaa ragse kaama celiso",
"Biya sar tegey waa la sugayaa",
"Biyahaan fiiqsi loo liqin, iyo hadalkaan fiirsi loo oran feerahay wax yeelaan",
"Biyo ay horotood dhooqo tahay, dabadooda maxaad mooday",
"Biyo gorore oo meel godan bay isugu tageen",
"Biyo meel godan bay isugu tagaan",
"Biyo sacabbadaadaa looga dhergaa",
"Biyo socdaa biyo fadhiyey kiciyaan",
"Boqol sano oo dawlad xumo ah, hal habeen oo dawlad la’aana baa xun",
"Boraan hadimo ha qodin ku dhici doontaa mooyee",
"Buubaal biyaha korkiisa saran buu ka didaa",


"Buur caws ah oo biyo ku agyaal baadi doonyoo biciidkuba waa",
"Buurta Saw iyo Sogsogley iyo Samow Boorame",
"Caana daatay dabadood la qabay",
"Caano baqay haddaad aragto, waa bi’iso naagood",
"Caano Jiilaal canba canbid",
"Caano yar iyo ciidan yarba marka la waayo ayaa la tebaa",
"Caasigaa iridkaaga ma mooga, baarri dadow dad kuuma noqdo",
"Cabaabiba cadaab bay ka subxaanalaysataa",
"Cadawgaa looma taahee, tun ku adkay",
"Cadho walaal waa la bariyaa (waa loo dulqaataa walaalkaa)",
"Cadku ceeji, xil iyo geeriba kuu dil",
"Calafkaa, nin ku rabaa baa haya",
"Caleen qudhac calool geel ma buuxiso",
"Caleen qudhac calool geel waxba kama tarto",
"Cali noolba wax sii",
"Calool adayg waa illaahay wehelkii",
"Calool rag waa webi xagaa",
"Canaan ka yaab ceesaan ma doojo(waa lagu canaanan dantaada looma seego)",
"Canaan ka yaab reer ma doojo",
"Canbe laf baa ku jirta",
"Canjeero siday u kala koreysaa loo cunaa",
"Caqli gaaliyo indho quraanjo lama arko",
"Caqli: Dugaag sankuu ka galay; Xoolo, sankuu ka galay; Rag, xabadkuu ka galay; Naago, indhuu ka gala",
"Car faruurow foori gaalee?",
"Carab iyo ilkaa cid isugu dhaw iyana weeys qaniinaan",
"Carab iyo labadiisa daan baa isugu dhaw iyana way is qaniinaan",
"Carab loaad caws looma tilmaamo",
"Caro walaal waa la bariiyaa (subax baa lala sugaa)",
"Carraabo, fadhaa quusiyey",
"Carrab dalab leh waa la gartaa, uur dadbanse lama garto",
"Carruurey cayntaa ba´day",
"Carruuri kor cabsooday leedahaye, kal cabsooda ma leh",
"Carruurta mulaca cayaar cayaar bay u dishaa, isagana waa u qur gooyo",
"Caruur gaalana ma aha muslinna ma aha ee waa kii lagu daraa",
"Caruuri waa ciil laga waynaado",
"Casaan qurux kama qatana",
"Casarkii wixii kugu dhacaa cishihii lagugu caayaa",
"Ceeb looma dhinto, cara lalama qarxo, cayna looma dhaawacmo",
"Ceebtaaday kow ogtahay, kun looma sheego",
"Ceel biyo lihi ma foga",
"Ceel dad liqa, ul baa lagu dayaa",
"Ceesaan ninkii weyddiinteda kugu dhiba kaxaynteedaa lagu dhibaa",
"Ceesaantii arigeeda diidda orgi shisheeyaa saarta (fuula, u baxa ama ka qabsada)",
"Cid wax kusiisa wax badan baad aragtaa, cid kla talisase wax yar",
"Cidlo ciirsi maleh",
"Ciirtaa dhamaa, ceebtaada yaqaan",
"Ciise socod kuma laabna, abeesona samir kuma laabna",
"Cirmigaagoo dheeraadaa geel dhalayana waa ku tusaa",
"Ciyaar baa dhab u gadoonta",
"Ciyi waa ka beryey",
"Ciyigii waa ka beryey qofkii cunay baa ka liita",
"Ciyowga habeen dhawaaqay wax uu ka cawduu dareemay",


"Col hortii baa hub la samaystaa",
"Col iyo abaar cagahaagaa lagaga baxaa",
"Col iyo nabad mid baa caynka lagu xejiyaa",
"Col ku galay cabsi kugu reeb",
"Col naago ka kacay iyo cadho nirig ka kcday midna ma sahal kuma qaboobo",
"Colka wadhaf ma lagu dayey",
"Colkaa ma dhamaadee ka kuu xigo ha u danbeeyo",
"Cudud caano gaabsheen cagaar ma korsho",
"Culimo dad u eki bay kugu dishaa, abeesona dhul u eki",
"Cuntadaan gacantaada ku jirin iyo afkaagu way kala raagaan",
"Daacadi ma hungowdo",
"Daahdaahow hortiis dafo waaye (Arrin degdeg u baahan lagama daaho sida heblaayo aad ogayd ooy hebel",
"Daawo tiro wax kuma tarto",
"Dab aan ku gubin kulaylkiisa ma ogid",
"Dab ama hadal baa lagu bakhtiiyaa ama biyo",
"Dab iyo xanuun meel ma wada fadhiistaan",
"Dab munaafaq shiday baa duul dhan guba",
"Dabaan kuleelkiisa la arag danbaskiisa lagama leexdo",
"Dabada iiga qor anigaa durugsan doonee (Ma dhiirrado nin aan garab wax lagula dhisayni)",
"Dabagaale timir gaari waayey qaraara buu yiraahda’",
"Dabalaay gooji ama ha goojin geela gu’ga dhalay uun baa lagugu tirin",
"Dabeecad xuma dad kaa saartay",
"Dabeecaddu diinta waa ka badh",
"Dabkii baxayaa dab lagu qabsadaa",
"Dacartuba mar bay malab dhashaa",
"Dacas iyo dameeraba lama kala laha",
"Dacas kaa wayni dhiiqaday kugu farjiyaan",
"Dacawadii tallaabada nebiga ku dayatay, teediina ka tagtay tu kalena gaari weydey",
"Dacawo duul-duul badan af libaaxeey dalaq dhahdaa",
"Dad iyo weel godanba waa la badsadaa (weelka godan biyahaa ku urura)",
"Dad kaa badan iyo biyo kaa badanba way ku hanfiyaan",
"Dad wax ugu liita ma tashe ma toshe ma tashiishe",
"Dad wax yar tare ma ahee, wax ma tare ma leh",
"Dad waxa ugu muran badan jaxar iyo jaahil",
"Dad waxa yaqaan nin tuugsaday iyo nin u taliyey",
"Dad waxaa yqaan nin tuugay iyo nin u taliyey",
"Dadku hadalkay isku afgartaan xooluhuna urta",
"Dadqal looma gurguurto",
"Dagaal qofbaa ku dhintee qof kuma dhasho",
"Dagaal wiil kuma dhashee, wiilbaa ku dhinta",
"Dal aqoon la’aan waa la habaabaa, dad aqoon la’aana waa la qadaa",
"Daleel marow maradiis geed ma daarow",
"Dameer dhaan raac",
"Dameer waa dameer sidii goodirkaba haw boodee",
"Dameeraha Adari qofkii oodda ka qaadaa aroorsa",
"Dameeraha Awdal ninkii ooda ka rogaa arroorsha",
"Dameeraha ta ugu xun baa ugu haraati kulul",
"Dameeraha ta ugu yar baa ugu biqlo badan",
"Dameeri dhaan raacday",
"Dameeri isku hallayn bay hooyadeed dabada uga nuugtaa",
"Dameero awdalan ninkii ooda ka qaadaa arooriya",
"Dameertu geel-didiska khuruf-khuruftay kaga dartay",

"Dameertu inta aanay cida baran ayey dhuusada barataa",
"Dameertu isku halayn bay hooyadeed dabada uga nuugtaa",
"Dameertu ma hadhsato ilmaheedana ma hadhiso",
"Dammeeraley Dad la xeer maaha",
"Dan iyo xarrago is weyday",
"Dan layskuma naco",
"Dani waa seeto",
"Dantaada derin karkaranna waa loogu seexdaa",
"Dantaada iyo madaxaaga midna lagama boodo",
"Dantaadana, maqaar eybaa loogu seexdaa",
"Dantii mooge, maro duuga ka liitee",
"Dantu ceebba ma lahee dadkuun baysku nacaya",
"Darandoorriyaaba naas-naasi (Nin ordaaba istaag)",
"Dardaaran caweysin kallah arooryaad buu leeyahay (Arrin la qorsheeyey meel laga bilaaboayey leedahay)",
"Dardaaran waa inta xayga la yahay",
"Dawaco geel ma cunto",
"Dawaco meeshay macal idood ku baratay, macaluul ugu bakhtidaa",
"Dawarsato dariiqay ku collowdaa",
"Deero waa dal maddays",
"Deriskaa dagaalkaaga rabaa, dooradaada ceshaas ku dhahaa",
"Deriskaaskaa marna ku dayo marna ku diin",
"Dhabada yari dhabada wayn bay kugu ridaa",
"Dhac dushii laguma wada hadlo",
"Dhadhan shaa waalan dhergaana ka sii daran",
"Dhagar qabe dhulkaa u dhaq-dhaqaaqa",
"Dhagax meel dhow buu ku dhacaa, hadalna meel dheer",
"Dhagax tuujin iyo taabasho waa isugu mid",
"Dhalaan dheelaa baradi, dhusuntaa far koo galiyee?",
"Dhalaan dheelaa baradi, dhusuntaa far koo galiyee = Dhalaan (caruur, ilmo, ubad) ciyaarta bartay dabaduu",
"Dhalaan qayladu waa qaboonada",
"Dhaliili dhaban bay ku taal",
"Dhalinyaro dhubuq dhubuq hore dhabana hays danbay leedahay",
"Dhallaan dhargay fartaa loo lulaa (way iska qoslayaan)",
"Dhallaan qayladii waa qaboonada",
"Dhar kaa dheer dhaxan kaama reebo",
"Dhaxal gorayo dhabad baa leh",
"Dhaxal goroyo dhebed baa iska leh",
"Dhedo roob noqon weydey",
"Dheere iyo gabane un baa jiree, Dhuubane majiro",
"Dheerow ii gaabow yaa jaree, dhuubow ma jaro",
"Dheg haddii la jaro daloolkaa hara",
"Dheg wax xun maqlaysaa wax wacan ma weriso",
"Dhegta hadii la gooyo daloolkaa hadha",
"Dheriga karkaa maxaa ka keenay, kulayl weeye",
"Dhib lagula qabo dhib ma eh",
"Dhicisku inta mindida loo soo siduu bakhtiyaa",
"Dhidar xabaalo qod bartay qudhin buu uga dhacaa",
"Dhiig islaan ma qarsoomo",
"Dhiil maran iyo dhiil buuxa la iskuma dhufto (Wax aan isu qalmi la isma dhaafsado)",
"Dhilaa la waaniyey markaasay tidhi ii dhakhsada rag bay sugayee",
"Dhillo, intaadan dhillo oran bay dhillo ku tiraahdaa",
"Dhilo garcatay mar horey ku nabad gashay",
"Dhoofaa kaa dhimay! (bal tan ka warran, ma run baa?)",
"Dhoofaa kaa dhimay",
"Dhool bari ka soo kacaa dhaan loo nageeyaa",
"Dhubuq-dhubuq hore dhabanahays dambey leedahay",
"Dhur waa la tegis bartay ka ridistu waa ku ceeb",
"Dhurwaa dhoomo laguma rarto",
"Dhurwaabaa lagu yidhi fool xumadaa, markaasuu yidhi walaalkay weerana ma aragteen",
"Dhuumashada dhabarku muqdo dhuumasho ma aha",
"Dib u gurasho dib bay kuu dhigtaa",
"Dibi hooyo xumi hore uma koro",
"Dibi hooyo xumi korme ma noqdo",
"Dibi hooyo xumi, hore ma noqdo",
"Dibi, bay waw dhutiyaa",
"Diinku ubadkiisa eegmaduu ku koriyaa",
"Dix dhaaxood dhagax ka waa, hayeesa hangool ka waa",
"Dixrigu(duqsigu) dantiisuu qudhunka ugu jiraa",
"Doc ka yeedh iyo dameerkaba daankaa la jebiyaa",
"Doofaarka ficil la’aan baa loo cadaabaa",
"Dooro hadey hal waddo iyo hadey toban waddo kurug, kurug ma dhaafeeyso",
"Dooro qoor qabasho biyo kuma cabto",
"Dooro xaarka way wada cuntaa, af-tirashadeyse isku dhaantaa",
"Doqon alle bariday xeradeeday ka aragtay",
"Doqon dib bay wax ka garataa",
"Doqon ha u gargaarin hana gargaarsan",
"Doqon iyo habeen baa madaw",
"Doqon milantay iyo geesi damac bartay dhexdoodaa miidaamo ka hacdaa",
"Doqon nebi Muusaa habaaray",
"Doqon qaddar alla taqaanna qulucdaada looma dhiibto",
"Doqon sokeeye maaha",
"Doqoneey dabkaa ba",
"Doqoni amaanay lahayn bay u rixisaa",
"Doqoni cad ciid loogu riday cay bay mooddaa",
"Doqoni calaf ma leh",
"Doqoni haddii nla xifaaltamo in la is diriray bay mooddaa",
"Doqoni hoosiis bay had mooddaa",
"Doqoni meeshii la isku diriray uun bay ogeyd, meeshii lagu heshiiye sema oga",
"Doqoni qiiq kama kacdee daamankay meer meerisaa",
"Doqoni saaf carro loogu riday, sad bursiinyo ma mooddo",
"Doqoni sokeeye ma aha",
"Doqoni waxay leedahay laba iyo toban indhood, hal mid waxay ku aragtaa",
"Doqoni xarigga lagu xiri xusulladay ku sidataa",
"Doqoni xin mooyiye, xisaab ma oga",
"Doqoniino waa shil",
"Doqonkii lumay oo la soo helay wuxuu yiri; “Maxaa la iiga farxi berriba waan lumiye",
"Doqonta usha agteedaa lagu dhuftaa haday garan waydana goshaa oo geshaa",
"Doqontu afka xanbay ku sidaa ishana xil",
"Doqontu hadalkay dib u gocotaa",
"Doqontu marka la ficil tamayo in laka tagayo ayey moodaa",
"Doqontu xeerna ma hoyso, xoolana ma hoyso",
"Dudumo dheeraataa dhulkuun bay ku noqotaa",
 "Dudun dareen iyo dugsasho,ha iskugudarin",
"Dudun dareen ii dugsashu inis ki dartooy",
"Dukhsi biyo ku dabaal bartay fuud buu ku bakhtiyaa",
"Dukhsi dantiisuu dumurka (qudhunka) ugu jiraa",
"Dukhsi dantiisuu dumurka ugu jiraa",
"Dukulush timir deeri waayi Kharaaraa tuf in erre?",
"Dul qaadasho yey noqon tii dibiga",
"Dumaal ni ka xishooday kama ilmo dhalo",
"Dumar iyo dheri toona yar yaraysi malaha",
"Dumar yaryaraysi male",
"Dumarka been baa lagu soo xero geliyaa runa waa lagu dhaqaa",
"Duqsi, caanuu ku dabaal bartaa fuudbuuse ku gubtaa",
"Durduro geel baa ku jaba",
"Durduro waxarood xanan(qodax) bay kula gashaa",
"Erey nimaan dhaafin odday ma dhalin",
"Ey is cunaysaa waraabe iskama celiso",
"Eydin geel kolba waa ninkii ku danbeeya",
"Eygii oo laf diiday ma noola",
"Faanoole fari kama qodna",
"Fadhi iyo fuud yicibeed laysku waa",
"Falaadhi gilgilasho kaagama godo",
"Fallaartii cirka loo ganay cid kastoy filo",
"Far bugtaa, Faro ka dheer",
"Far iyo meel bugtaa is og",
"Far kaliyihi waji ma maydho",
"Far keliya Fool ma dhaqdo",
"Faras aanad lahayn fuul madiisa futaqaradh baa laga qaadaa",
"Fardaha dheereeyaa Fagaarahay isku arkaan",
"Fardo laysu hayo maxaa laysugu faan",
"Farihii dufan leh ayaa wax duuga",
"Faro ka ciyaar dabo ka ciyaar baa dhaanta",
"Farsamo xumo, futada cankeeday ku goysaa",
"Faruurow maxaa berbera ku geeyey? Dee faduul!",
"Fulay hooyadii ma goblanto",
"Fulay wax ka wadne weyn",
"Fulay wax ka qoryo badan",
"Fullaw guuli kuu dhawaydaa",
"Futo iyo dhul isma huraan",
"Gaal dil gartiisana sii",
"Gaashaan qaad ma anbado",
"Gabadh nin dhali karaa dhiqi kara",
"Gabadha dheg-dameer in leeg baa ku dansanta wiilkana in til leeg baa ku darsanta",
"Gabadhi waa meel xun joog",
"Gacani waa miskiin",
"Gacantaadu hadday dhudhub gasho, lagama dhuftee waa laga dhirindhiriyaa",
"Gacmo wada jirbay wax ku goyn karaan",
"Gadal gadaal geed looma koro",
"Gadhba gadhbaa la tusaa",
"Gar dabadeed, guu-guu (gunuunuc) baan nacay",
"Gar waa loo wada islaam",
"Gardarraa ma guulaysto",
"Gardarro looma garbo yeelo",
"Gari ilaahay bay taqaan",
"Gari laba nin kama wada qosliso",
"Gaws iyo gustoona layskuma ag dhaqdhaqaajiyo",
"Geed joog gartii waa yaqaan, laga dhimayna dhaxalkii waa yaqaan",
"Geed walba in gubtaa, waa hoos taal",
"Geel carruuri qaaday ma foga",
"Geel caruuri qaaday ma foga",
"Geel darreeray nin ka dayrshay ma awliya Allaa",
"Geel indho kuul muxuu ka kasaa?",
"Geel laba jir soo wada mar",
"Geel soddon qaday, saddex kuma dari waayo",
"Geeli waa geel, wixii gooyaana waa geel",
"Geel-jire isagooy ushu u goantahay ayuu xaggeen ka goostaa ku yidhaa",
"Geeljire, geela waa wada jirtaa, waana kala jirtaa",
"Geelow geed walba daaqdaye, markaad Ciin daaqdaa laguu yaabaa",
"Geeri nimaan aqoon iyo geel jiray ku wanaagsantahay",
"Geeriyu nin aadan aqoonin iyo geeljiray ku roomntahay",
"Gees loaad kulayl kaa lagu jaraa",
"Gees lo’aad kulaylkaa lagu gooyaa",
"Geesi allaahay ma xilo",
"Geesi, Alle ma xidho",
"Gobanimo waa joome",
"God hadimo ha qodin, haddaad qoddana ha dheerayn, ku dhici doontaana ma ogid",

"God mar ku asturay xumaantiisa lama sheeg sheego",
"Gorayo la hub sayoo haad bay noqotay",
"Gorgor, haadda ka weyn",
"Gorgortan saaxiib iyo walaal toona ma yaqaan",
"Gudineey ima goyseen, haddaan badhkay kugu jirin",
"Gudini geed ma goyseen, haddaan geed kale ku goyn",
"Gumur uraasa, weyne gurudee (gumur wey urtaa waana lagurtaa)",
"Gurbaan Garabkaaga ha kuugu jiro ama gacalkaa hakuu hayo",
"Guur marka hore waa sino dhuuban yahay, marka dambena waa sino ballaaran yahay",
"Guursato loo galmoon og",
"Haad habeen kacay waxbaa kiciyey",
"Haani guntay ka tolantaa",
"Habaar waalid ma hadho",
"Habar baas inan baas bay ahayd",
"Habar caal weydey durey bay hafartaa",
"Habar dhali wayday aleelo ku waalatay",
"Habar fadhida legdini wax uga fudud",
"Habar Jeclo, hadalka dib bay u gocotaa",
"Habar roob hayo, ta kalena inuu hayey modaa",
"Habeen ciidan maaha",
"Habeenkii hoos baa loo hadlaa maalintiina hareera haa layska eegaa",
"Hadal aan fiiro loo odhani wuu kula fogaadaa, caano aan fiiqsi loo dhamina feedhahay wax yeelaan",
"Hadal badani haan ma buuxsho",
"Hadal hadal kama dheera",
"Hadal intaadan buu ammaan yahay",
"Hadal iyo hablaba duco la’aan bay tarmaan",
"Hadal iyo hilbaba kala qalan",
"Hadal lama wadaagee caanaa la wadaagaa",
"Hadal nin badiyeyna ma dhamayn nin yareeyeyna waxba kama tegin",
"Hadal nin badiyeyna ma wada odhan, nin yarreeyeyna kama wad tegin",
"Hadal nin si u yiri, ninna si u qaaday",
"Hadal tuurtuur kuma sama",
"Hadal waa dheh iyo dhagayso",
"Hadal waa la kala odhan og yahay illaahayna waa la kala bariyi og yahay",
"Hadal waa margi",

"Hadal waa mergi hadba meel u jiidma",
"Hadal waayeel waa guudmar",
"Hadal yar iyo hawl badan",
"Hadalaw nin si kuu yidhi hawraarayna ninba si kuu qaaday",
"Hadalka kiisa kulul iyo kiisa qaboobi meel buu isugu tagaa",
"Hadalka wanaagsani waa sadaqo",
"Hadalku intuu uurkaaga ku jiro ayuu amaanadaa yahay",
"Hadalku intuu uurkaaga ku jiro ayuu ammaano yahay",
"Hadalna sii dhehbaa diley hanbana sii hudhbaa dishay",
"Haday fooli timaado gudo qarsiimo reeban",
"Hadba sidii loo jabaa loo dhitiyaa",
"Haddaad been sheegayso been run u eeg sheeg",
"Haddaad hungurooto waa la hadlaa oo habaa la dhisaa wax laug helo",
"Haddaad tagto meel lagu il laayahay ishaa layska ridaa",
"Haddaan sacabka xeeli ku jiran, maxaa habeenkii loo tumaa",
"Hadday curaddii durdurisay aaran maxaad moodday",
"Hadday degdegsiiyo door dhalaan, kaadsiiyana kiish lacageey dhalaan",
"Hadday tubaako, faa’iido leedahay Habargidir baa liqi lahayd",
"Haddii aan la kala roonaan roob ma da’o",
"Haddii uu deg degsiinyo door dhalo raagsiin yuhuna kiish lacaguu dhalaa",
"Haddii lagu sheego waa lays sheelaa, haddii lagu sheelana waa lays sheegaa",
"Hadii aad dhimanayso dhareerkaa layska duwaa",
"Hal diidaysaa geed ay ku xoqato ma weydo",
"Hal libaax arkaysaa ma godlato",
"Hal libaax arkaysaa ma godlato",
"Hal maqaarka diidaysaa daldalool bay ka eegtaa",
"Haliba wiilkay korisaa, wedkeeda leh",
"Halmaan hadal kuma jiro",
"Hamba soor ma eh",
"Hangaraarac lug uma dhutiyo",
"Harag sagaaro iiga kac ma ahee iiga durug ma leh",
"Hasha naasa adag iyo weedha (hadalka) maxaa kulmiyey",
"Hashu ragaadka, maysku eryeysaa, mise wayska bixinaysaa",
"Hawli jid caddeysay",
"Hawo iyo hoos galbeed labadaba lama gaadho",
"Heeraa wan ma eh",
"Heesta geelu waa kala horreysaa",


"Hilib beer laga dooray waa weyd",
"Hilib hal dukhsi ayaa qudhmiya",
"Hillaac biyihiisuu muujiyaa",
"Hoonbaro libaax bay soo wadaa",
"Hooyadii ka guure habar yartii kuma negaado",
"Hubkaaga iyo hayinkaaga, midna laguma hodmo",
"Hubsiimo hal baa la siistaa",
"Hunguri wax ka weyn la mariyaa wuu dillaacaa",
"Hunguri weyni kuunto weyni baa laga qaadaa",
"Hunnu hunnu hadal maaha, himbiriirsi arag ma aha",
"Hurdo cagahay ka bilaabataa",
"Hurdo habar ma koriso",
"Ibtileysan ayaa belaayo tilmaanta",
"Il ibtilaysan ayaa balaayo tilmaanta",
"Illeyn doqoni qiiq kama kacdee daamankey meer meerisaa",
"In habari gasho, hali ma qaado",
"Inantay hooyadeed hadhuudhka tuntaa iyana haadintay barataa",
"Inantii hooyadeed hadhuudhka tuntaa, iyana hufkiyo haadiskay barataa",
"Indho is jecel isma eegi karaan",
"Inneen daaman nool ma daalaan, oo dad baan nahay kaama daayaan",
"Inta aanad falin ka fiirso",
"Inta gaari la doon-doonayo, ayaa goombaar wiilkeedu ciidamiyaa",
"Inta Jiillaal loo adkaysto, jir looma adkeysto",
"Intaadan falin ka fiirso",
"Intii orod jirey, kuftinna way jirtey",
"Irrid af ma daboole ee ood baa daboosha",
"Ishaadaa kuu macalin ah",
"Ishaadu waa kula da' dhegtaaduna way kaa da'wayn tahay",
"Ishaaduna waa kula fil, dhegtaaduna way kaa weyntahay",
"Ishiisa laga gartaa, Ushiisa lagu tumaa",
"Isla weyn, dooro weyn",
"Isma hubsato aroorkeeda ka mashxaradaa la yidhaahdaa",
"Isma'og aqalkiibay aslaysaa",
"Isu qabe aan loo qabin",
"Jacayl biri ma gawso",
"Jacayl Biri ma goyso Biyana kaama maydhaan",
"Jidh qalaad waa dhul qalaad",
"Jiid aan ku jiidee waa gacmo daalis",
"Jinni, Ninkii keenaa bixiya",

"Kaadi badane waa loo gogol badiyaa",
"Kab xume ma hadho ee kab laawaa hadha",
"Kaftan iyo kaadi baa laysku cadaaba",
"Karis xun iyana ku wax la",
"Kelyo nimaan lahayn bay kaadiyi dishaa",
"Kibir waa lagu kufaa",
"Kibir wuxu kaa saaraa hadhka meelse kuma geeyo",
"Kibiraw kab iga xoor faanawna far iga jabi",
"Kitaab gurigiisii loo diiday, sayax Illaah baa baday",
"Kitaab meelaan lagu fasirayn laguma furfuro",
"Kolka waylaha la helo ayaa loodana la maalaa",
"Kuftin jillib iyo habaar waalid midina sahal kuma hadho",
"La jiifiyaana bannaan, La joojiyaana bannaan",
"Laabtu low ma aha hadba la laalaabi karo",
"Laba layskuma daro: bidaar iyo timo, baryo iyo ad-adayg",
"Laba qaawan isma qaaddo",
"Laba tallaabo dhexdood baa talo ka dhalataa",
"Labaatan jir intuu geed ka booduu talo ka boodaa",
"Labadii qaydhin ku qaybsatay bisayl iskuma cawrido",
"Labadii xaqdaro ku heshiisa xaqay ku diriraan",
"Labo bukta ma is baaniyaan",
"Labo qaawani isma qaado",
"Lacagina lacag bay dhashaa injirina qindhicil",
"Laf jabtay sideedii ma noqoto",
"Lafo geel iyagaa laysku jebshaa",
"Lama gano falaadh kugu soo noqon doonta",
"Lama huraan waa caws jiilaal",
"Lax gawracan maqaarsiib kuma xanuunsato",
"Laxi shilalkay is dhigtaa lagu qalaa",
"Layligu kasha biyihiisa ku jiruu ka didaa",
"Libaax aan dhiig dhadhaminini habeen ma ciyo",
"Libaax deeqi ka gurxamisay",
"Libaax intay bulbushu ku taal, bahal ma cuno",
"Libaax lab god lagama kiciyo",
"Libaax nin aan aqoon baa lax ka rida",
"Libaax nin ganay iyo nin galadayba og",
"Lixdan jir laguma helo qiimigaad laba jirkaa wayday",
"Loogow laguu minan fadhiyee",
"Lugtii jeeniga dhaaftaa way jabtaa",
"Luuqun dheeraatay madax ma dhaafto",
"Luuq luuq maraw laasim laamiguu iman",


"Musqul nin galay muraad buu leeyahay",
"Muruqa laba suulle ninba si ku ah",
"Muraadka magaalo kaa gala muraayad baa kaa xigta",
"Mukulaal minankeedii joogtaa miciya aar bay leedahay",
"Mugdi, arlaada geed ii goduh",
"Mudduci markhaati leh ayaan maankay ka waayey",
"Misbax minankaga u mugdi ah, minan dadow ma loogu nureyo?",
"Midho gunti ku jira midho geed saaran looma daadsho",
"Midho daray duuduubkaa lagu liqaa",
"Mididii qooqdaa dib bay u qaddaa",
"Min haddaad gasho meelo daydaye lama noqdo",
"Milil hoostii lama dhayo, haddii la dhayana qudhun baa looga dhacaa",
"Miidaamo dhega maleh hadduu malag dhawaaqaayo",
"Madiidaan la'aan waa la midgoobaa",
"Midho geed saaran, kuwo guntiga ku jira looma qubo",
"Meeshaad ku qoydid baa laysku qallajiyaa",
"Meelaad madaxeeda tahay, mijo lagama noqdo",
"Meel hoo u baahan hadal wax kama taro",
"Meel hal lagu qalay mana hadal yara mana hilib yara",
"Maaweelo ma bogsiiso meel ku bugta",
"Meeshay caruurtiyo dumarku kugu bartaan waa laga guuraa",
"Meel Aar ka kacay buu Atoor fadh-fadhiistaa",
"Meel aanad seexan doonin laguma luloodo",
"Maxay ka nuugtaa ama ku nuugtaa, dibno iyo naaso midna maleh",
"Matag meel kuguma simo",
"Maska madaxaa laga dilaa",
"Masiibadu adduunyada iyadaa u macallin ah",
"Mas iyo digaag daris ma noqon karaan",
"Mas abur buu dhalaa, aburkuna mas buu dhalaa",
"Martidu marka hore reerkaa ka naxa marka dambana iyadaa kala naxda",
"Martidu iyadaa kala naxda",
"Marti nin ka yar iyo muddo maalin ka yar midna lama arag",
"Marti loo qalay in lala qabay mooddaa",
"Marti iyo maydba waa la muquunshaa",
"Maroodi takarta saaran ma arkee, ta kale saaran buu arkaa",
"Markuu kuu soo socdona warbuu kuu soo sidaa, markuu kaa sii socdana war buu kaa sii sidaa Marba sidaad u jabtaa loo dhutiyaa",
"Mar i dage alla ha dago, mar labaadse anays dagay",
"Manjo dhooqo leh, marba mid baa la siibaa",
"Manjo dhooqo leh, kuwo dhaqanaa ka roon",

"Manfac haddii lagu siiyo, murdiye lama noqdo",
"Mala-duul wuu guulaystaa xin u duulse wuu guul darraystaa",
"Magaalo qayrkaana u cay adiguna ha deynin",
"Madax muuqda iyo mindi saawira midna lagama samro",
"Madax meel ka sarraysa oo la taabtaa ma jirto",
"Madax aanad lahayn miyirkiisa laysma saaro",
"Macal cune muuqan doonee",
"Maba lulatee maxay leeftaa",
"Maantana far baan maydhayaaye hay fadhiyo geelo",
"Maalintii oday oday baa loo shiraa, habeenkiina habar habar",
"Maalintii intay ishaadu gaadhaa la hadlaa, habeenkiina inta gacantaadu gaadho",
"Ma xasuuste isma xabaalo",
"Ma waxaad yeeshaa, wax naftaada u fiican oo wiilkaaga u xun, mise wax naftaada u xun oo wiilkaaga u fiican",
"Ma taagtaa baad guurtaa, mise taako-taako",
"Ma sugto, Meher ma leh",
"Ma nimaan wax aqoon baad wax la qaybsataa, mise baddaasaad dhurtaa",
"Ma ciil sokeeyaa ku haya, mise ciddi hoosteedaa lagaa hayaa",
"Naag kun baa koodisa, kow baana guursada",
"Naag, naag ka umulisay iyo nin reer u weyni, midna siday wax u ogyihiin uma sheegaan",
"Naagaha iyo carruurtaba sasabaa lagu wadaa",
"Naagi kun nin way la sheekaysataa kawna way ka guursataa",
"Naagi naag lala qabo waa u col",
"Naagi nimay legdaan, kama kacaan",
"Naagi ninkay legedo kama kacdo",
"Naago abaal ha u gelin amaahse ha u diidin",
"Naago badhaadhahooday ka sheekeeyaan, ragna ba’ooda",
"Naago been baa lagu soo xero geliyaa runna waa lagu dhaqaa",
"Naago iyo riyaba diifta ayey isku eryoodaan",
"Naago jileec iyo naxariis midna wax kuma laha",
"Naago nimaan maddaxooda maja u rogin nin ma moodaan",
"Naago nin ay yaqaaniin col ma moodaan",
"Naago waa belo loo baahan yahay",
"Naago waa u samir ama ka simir",
"Naago wax laga bixiyey laguma dhaqo oo wax loo hayaa lagu dhaqaa",
"Naago yaryarasi ma le",
"Naagtii caana xun dhigataa iyana ku murud la’",
"Naaguhu hoosiis bay hadh moodaan",
"Naar hooba galaaso bartaa ey la aragneey, tiimbooy (Naar si fiican baa loo galaa, hadii kale banaankaa laga joogaa)",
"Naaso kor u jeeda nin arkaa, kuwo hoos u jeeda ma arko",
"Nabad la’aani waa nolol la’aan",
"Naf wax jecel allaa dhibay",
"Nafeey, nin ku doona ku waa",
"Nafsi raaga rag iyo geel baa iska leh",

"Nafsigu ma hadho",
"Naftu orod bay kugu aamintaa",
"Naftu waxay ogtahay ilaashataa",
"Naxariis eebbe lagama quusto",
"Nimaad dhashay kuma dhalin",
"Nimaad fadhiga kaga adag tahay looma saro kaco",
"Nimaad kabahiisa tolayso, kafantaada tolaaya",
"Nimaad kabo ka tolanayso kabihiisaa la eegaa",
"Nimaan balan lahayni waa nin aan diin lahayn",
"Nimaan dhididin ma dhergo",
"Nimaan dhul marin dhaayo malaha",
"Nimaan hadlin habartiina wax ma siiso",
"Nimaan hubsiimo lahayni war gal maaha",
"Nimaan kuu furu doonin yuusan kuu rarin",
"Nimaan naxariisan looma naxariisto",
"Nimaan qaybin jirin haduu qaybiyo nimaan qadi jirin baa qada",
"Nimaan qooq dilin maroodi ma dilo",
"Nimaan shantaasi kaa dabaalin sharci kaama dabaalo",
"Nimaan shaqaysan shaah waa ka xaaraan",
"Nimaan shaqaysan shaxaad baa dila",
"Nimaan waxa jooga garanin waxa soo socdana ma garto",
"Nimay meeli buktaa isagay balbashaa",
"Nin aad kabtiisa tolaysaa, kadabkaaga jaraya",
"Nin aan baqani ma bad baado",
"Nin aan dhididin ma dhargo",
"Nin aan dulqaadasho lahayni waa geel aan horwayn lahayn",
"Nin aan hadlin habartiisba qadisay",
"Nin aan kuu furayni yuu kuu rarin",
"Nin aan maahmaahin cod kar maaha",
"Nin aan wax garad ahayn haanta gadaankeedaa wax loo saaraa nin wax garad ahna daaqsin geel",
"Nin aanad maalin ku baranin sanad kuma baratid",
"Nin abaal gala wax badan baa la arkaa ninse guda wax yar baa la arkaa",
"Nin ani yidhi dad iska saar (sooc)",
"Nin buka boqol u tali",
"Nin casarkii isa sheegay, cishihii ceebi ma qabato",
"Nin daad qaaday xunbo cuskey",
"Nin dameero dabadood ka degay meel uga tooban buu waayey",
"Nin dameero rartaa dad la toy ma aha",
"Nin dhintay kabihiisaa dhaama",
"Nin durbaan tumay ilaaq dalbay",
"Nin durbaan tuntay ilaaq dalbay",
"Nin duulay dantii kaa og",
"Nin faash wataa xaabo ma waayo",
"Nin fadhiya, looma saro joogsado",

"Nin faruurani ma fooryo",
"Nin gu kaa wayn garaad kaa wayn",
"Nin hadduu isukaa waalo waa laysla waalaa",
"Nin ilko waa wayn haduu dhintona inuu qoslayaa la moodaa",
"Nin Illaahay ka dambeeya kabtii ma yeela",
"Nin is faanshay waa ri is nuugtay",
"Nin iyo naag is qaba colna ma aha nabadna ma aha",
"Nin iyo qabkiis",
"Nin jiifa lama legdo",
"Nin kaa wayna waxba looma sheego",
"Nin kaligii tashaday waa nin orgi rartay",
"Nin keligii garramay, iyo nin dhul gannay midna ma gefo",
"Nin ku arkaaya looma saro kaco",
"Nin ku necebi xantaa og, nin ku jeclina xogtaa og",
"Nin kuu digay kuma dilin",
"Nin la dhacay ama caytan ama habaartan",
"Nin la sugayoow adna yaad sugin",
"Nin lagu seexdaw ha seexan",
"Nin maalin ma gaadhid, nina sanad ma gaadhid, nina weligaaba ma gaadhid; nin maalin ma gaadhid oo waa ninka kaa faraska dheereeya, nin sanad ma gaadhid oo waa ninka xoolihiisu sanadkaa meel caws badan daaqiyey, nin weligaa ma gaadhid oo waa ninka kaa gabadha/naagta wanaagsan",
"Nin magaalo ka dudaw siigo yare",
"Nin mar waashay waalida loogama sheekeeyo",
"Nin nin kaaa xigo iyo hawl nin kaa xigo midna laguma deg dego",
"nin ood sida iyo nin adhi la joogaa arin ma kala laastaan",
"Nin ooman biyaha hoo baa deeqa",
"Nin qoyani, biyo iskama dhowro",
"Nin qurux badan naagtaada uga yaab nin fool xuna naftaada uga yaab",
"Nin rag ah looma duur xulo",
"Nin reer ugu wayn iyo naag naag ka umulisay midna siday wax u arkaan uma sheegaan",
"Nin sigtay ma nabad gelin",
"Nin soo fadhiiso laga waayo soo seexaa laga helaa",
"Nin soori kaa qaaday waa nin seefi kaa qaaday",
"Nin tuur lihi sida uu u seexdo isagaa kaa yaqaan",
"Nin waalan tolkii baa u miyir qaba",
"Nin walba intay taagtii tahay baa qoraxdu ugu tagtaa",
"Nin walba meeshii buktaa belbesha",
"Nin waliba waxa uu yahay ayuu ku moodaa",
"Nin war kuu keenay war kaa qaad",
"Nin wax dhaqay dhurwaana wax u dhaq",
"Nin wax yaqaan daaqsin geel baa wax loo mariyaa, ninaan wax aqoonna qaanso qurqurkeed",
"Nin wayn tag lama yidhaahdee wuxuu ku tagaa la tusaa",
"Nin wayni waa qorax casar joogta",
"Nin wayni wadkiisa waa yaqaan",
"Nin xil qaaday eed qaad",

"Nin xoola ku siiya in badan baad aragtaa, ninse talo ku siiya wax yar baad aragtaa",
"Nin yari waa nin ban soo ordaya",
"Nina dabeecadiisa lama doorin karo",
"Ninaan hadlin, hooyadiis qadisay",
"Ninba curadkiisa ceel gee",
"Ninba gurigii gaado ku leh",
"Ninba kaskiisuu kor tagaa",
"Ninka aan hadalka suginin, warrankana ma sugo",
"Ninka aragiisu ku deeqo ayaa oontiisuna ku deeqdaa",
"Ninkaad adhi weydiisanayso, geel weydii",
"Ninkii belaayadaada raba, bawdkaagu qori ka jabsadaa",
"Ninkii dhagar qaba dhulkaa u dhaqdhaqaaqa",
"Ninkii dhimanayaa dheg baa dheer",
"Ninkii geed fuulay asigi lee kasoo degi",
"Ninkii seexdaa sixii dibi dhalay",
"Ninkii talin jiray hadduu tago, midaan talin jirin baa yimaada",
"Ninkii tiisa daryeelaa tu kale ku dara",
"Ninkii uurka dabana Illaah baa arka, ninkii isha dabana Aadmibaa arka",
"Ninna caadidii ma daayo, bahalna ceedhin ma daayo",
"Nin meeli u cadahay meeli ka madaw",
"Nin caadadii ka maydh iyo dundumo ciid ka maydh labadaba waa lagu daalaa",
"Nin dheerna waxba looma tilmaamo",
"Ood is qabsatay maroodina way qarisaa",
"Ood kaa dheeri kuma dhaxan tirto",
"Ood qaadis iyo jiidis waa isla guri geyn",
"Oodi siday u kala sarreeysaa loo kala guraa",
"Oodo dhacmeed siday u kala sareeyaan baa loo kala guraa",
"Qaadis iyo jiidis waa isla guryo geyn",
"Qalbigu laba ruux ma wada qaado",
"Qawl nin wayn ka dhacay waa qolof geed ka dhacday",
"Qaybshe qad ama qaaday",
"Qof aan waxa soo socda garan waxa joogana ma garto",
"Qof caashaq hayaa wax ka calaancal badan",
"Qof nool oo ku hortaagan lagama quusto",
"Qof walba qumanihiisaa qoorta ugu jira",
"Qof waliba wuxuu dhigtuu dheeftaa",
"Qof waliba intuu cunuu ciidamiyaa",
"Qofkii aragiisu ku deeqaa oontiisuna ku deeqdaa",
"Qoryo adistooda isku duwis baa horreysa",
"Qosol badani qoonsimaad noqoy",
"Qosol hiil leh",
"Qosol qoonsimaad noqay",
"Qufac iyo uur midna ma qarsoomo",
"Qunyar socde qodaxi ma mudo",
"Quruxi waa ishaada, qiimana waa ayaankaaga",
"Quud aan jirin qoryo u guro",

"Raad arrooryo dib looma raaco",
"Rag saddex ka oggow: Gacan gudhan, gar weecsan, iyo guddoon jilicsan",
"Rag gar baa kala saarta dumarna jaan",
"Rag hunguri buu isku raacaa",
"Rag jidiin baa walaaleeya",
"Rag la’aan waxba kuma yeeshee Rag xumaa ku disha",
"Rag qawl baa xidha dumarna meher",
"Rag sadex lama raaco, ma fakere,ma faaidayste,ma foorarsade",
"Rag waa arin keen iyo aqbalkeen",
"Rag waa raggii hore hadalna waa intuu yidhi",
"Rag waa shaah dumarna waa sheeko",
"Rag walaalow wuxuu ku dhaamo la waa",
"Rag waxa ugu faan badan mar dhoof iyo mar duul",
"Rag waxa ugu liita ciil kama baxe iyo calooshiisa la ciyaare",
"Rag waxa ugu liita looma maahmaahe, looma sheekeeye, looma soo gale",
"Rag waxa ugu liita, ma hadle ma heenseeye, ma haasawshe",
"Rag wuxuu kugu bartuu kugu dilaa",
"Ragi sadex bay ku kala baxaan , wax tegay ka hadhidii, wax jooga ka hadalkii, wax soo socda ka haloosigii",
"Ragu sadex waa iskaga mid",
"Magaca, magta iyo maganta",
"Ragu waxa uu ka sheekeeyaa biiisa dumarkuna badhaadha hooda",
"Reer ba’ow yaa ku leh!",
"Reer guura raac iyo carruurba loo kala sheekeeyaa, is mase arkaan",
"Reer, naagbaa kaa raacda",
"Reerka meelan loo husan looma haatiyo",
"Ri waalan ridaada laguma xidhto",
"Riyuhu lugtooday shalan ku doontaan",
"Roob magaalo ku hooray ramaas soo bixin maayee laamiguu ku raftaan",
"Run iyo ilkaba waa la cadeeyaa",
"Runi rag kama nixiso",
"Ruux aan geeri iyo nolol midna ahayni/ ma dhiman mana noola",
"Ruuxba dhiishuu ruxduu caanaheeda dhamaa",
"Saddex baa la yidhi: Lixdan jir lexojeclo ha la wadaagin; afartan jir ha la garramin; labaatan jirna ha la legdemin",
"Saddex baa rag u liita; Ma toshe, ma tashade iyo ma tashiishe",
"Saddex Ilaah waa karaa, mase suurowdo: Ilaahow guursan maayee wiil i sii; Ilaahow shaqaysan maayee xoolo i sii; iyo Ilaahow ku caabudi maayee jannada i gee",
"Saddex lama arag: Marti nin ka yar, muddo maalin ka yar, salaad ragcad ka yar",

"Saddex lama raaco: Ma horreeye, ma hambeeye, iyo ma haasawshe",
"Saddex looma adkeysto: Gaajo guri og, gardarro garab og, cudur geeri oh",
"Saddex markaan bartaan ka gaboobay: Dab ollolintiis, carruur aamusinteed, iyo awr carraabintiis",
"Saddex wer-werkay kugu kordhiyaan: Faraska xun, naagta xun, iyo hoyga xun; haddana saddexdaas baa kaa bi’iye",
"Saddex col baa jira, col cad , col cas, col madaw, colka cad waa biyaha, colka casna waa dabka ,colka madawna waa dadka",
"Saddex la lama dego, doqon fiiro taqaan, fulay daandaansi yaqaan iyo geesi damac yaqaan",
"Saddexna la lama saaxiibo, nin aan rabi aqoon, nin aan rag aqoon iyo nin aan run aqoon",
"Safar waa si wada yeel",
"Sagaaro intay tub joogto bay tub kale dayataa",
"Sagaaro inteeda waa ku duq",
"Sagaaro laba cad oo la kal qaado ma leh",
"Sagaaro, mindhaa ima barato",
"Sahaydaa waa hor, socodkaana waa dib",
"Sakaaro laba tun oo laka qalo ma leh",
"Salaadba waqtigeedaa la tukadaa",
"Samraa, sammo hela",
"Sankaagoo qudhma lama gooyo",
"Seedi waa beer",
"Shan nin oo shidho qayb leh, hal shanshaa ka baxda, shan ninnaan shidho qayb lahayna, shan shanshaa ka baxda",
"Shan shidda ma macaysaa",
"Shinbiri maalibay dab qaaday buulkeedii baanay ku gubtay",
"Shiikh markiis yimaado, shariifku, shubaakaduu ka baxaa",
"Shinbir duul duul badani af libaax bay gashaa",
"Shinbirba shinbirkiisuu la duulaa",
"Shinbiri laba geed ma wada gurato",
"Shir looma wada uunsiyo",
"Shir naagood oo shan dhaafay waa shar",
"Shisheeye sheela duxa ma leh",
"Shubaali waa biyo la bax",
"Sidaan kuugu lisay iigumaad hanbayn",
"Sidee xeego lagu xagtaa ilkana u nabad galaan",
"Sir ma qabe allaw sahana",
"Sir naageed lama sal gaadho",
"Si xun wax u sheege saaxir ka daran",
"Sodcaal maa moodhar, sahayna waa lacag, saaxiibna waa kaba cad",
"Soo bax baa la leeyahay sacabka leefaysaa",
"Soo joogso laga waayaa, soo jiifso laga helaa",
"Soomaalidu been way sheegtaa beense ma maahmaahdo",
"Soomaalidu waxay casarkii kugu aragtay cishihii kugu caydaa",
"Soomalidu waa indho ku garaadle",
"Soor quudheed lama cuno xoolo quudheedse waa la qaataa",
"Soori waa in xil lagaga tago iyo in xarrago lagaga tago",

"Tabcadaa ma tuugoobo",
"Talo adigaa ku nool ee iyadu kuguma noola",
"Talo laba adin dhexdood bay ka dhalataa",
"Tol la’aani waa tows",
"Tol yarraaday, tafo naagood baa laga dayaa",
"Toladu waa mar aad gaadhi waydo iyo mar aad garan waydo",
"Tolkaa maw talisay, mase tuugtay",
"Tolkaaga iyo xaaskaaga midna looma xoog weynaado",
"Tuhun waa sed",
"Tuug la qabtay talo ma laha",
"Tuug tuug ma xado",
"Ul jiiftaa ma jabto",
"Umili ilawshiinyo dhaw",
"usha intay qoyan tahay ayaa la toosiyaa",
"ushaada nin aad ka qaadi kartaa loo dhiibtaa",
"Uur mudane iyo uur Berde, midna lama baadho",
"Waa baahan tahay bakhtiga looma cuno",
"waa lagu shareeraa waxay sheegtaba ha waydee",
"waalida ninkii soo baraa laga waraystaa",
"waan xoolo yarahayna deeq lagagama hadho waan dad yarahayna dagaal lagagama hadho",
"waano dhalan baa ka adag(ka roon)",
"Waari mayside war hakaa hadho",
"Waayeel ha soocine, wax aqoonta sooca",
"waayeel hadalkiisa kaftan buu ku dhamaystaa",
"waayeel hortiisaa caano loogu badhxaa",
"Wadaad waa nin",
"Wadaanta isha ka xumaataa, faylkay la tagtaa",
"Wadaantii geeleeda kaafida, baa mid kalena kaalmeysa",
"Wadar iyo waaxid yaa waalan",
"wadiiqada yari wadada wayn bay kugu ridaa",
"Wadiiqada yari waddiqada weyn bay kugu riddaa",
"wakhti kaa lumay muruguu reebaa",
"wakhti kaa tegay tiigsimaad maleh",
"Walaalkaa dhuux tagoogaa loogu soo subkadaa (dhaashadaa)",
"walaalkaa markhaatiga ku fur magtana la bixi",
"walaalo is necebi way xoola yareeyaan wayna xabaalo badiyaan",
"walaashaa iskuma hubtida seedigaa haysi seegina",
"wan wayn jeeroo la gawraco indhihiisu cirka ma arkaan",
"war jiraaba cakaaruu iman",
"war la’aani waa dhego laaan",
"war xumi dugsi ma fadhiisto",
"waraabaa yidhi ulna layla gaadhi waa cayna wax igama tarto",
"Waraabe daalay, dirirtiisaa loo tagaa",
"waraabe dhankii loo eryaaba waw toos",
"Waraabe ulla lala gaadhi waa, orodna wax lagaga dhibi waa",
"waranka ninka kugu dhufta iyo ninka kugu dhaqdhaqaajia ninka kugu dhaqdhaqaajiya ayaa xun",
"Wax aad baratay waa baaskaa",
"Wax aqoon wax looma sheego",
"wax is waydiintu ma xumee wax is waydaarsigaa xun",
"Wax la dhalay iyo dhul baa loo marti yahay",
"Wax la qarashaa ama qudhme ama qubte",
"wax raagaa rag kuma sama",
"Wax rag kaa galay rako kaa gale",
"wixii ay idho arkaan ayey ilko gooyaan",
"wax walba run moodaa rag ugu liita",
"waxa jira sadex abaar, abaar geel, abaar dumar iyo abaar rag; Abaar geel waa ilko laaan, abaar dumar waa ubad laaan, abaar ragna waa arin laaan",
"Waxaan calaf ahayna lama cuno, waxaan hed ahayna looma dhinto",
"Waxaan kashaada gelin, korkaaga yay dhaamin",
"Waxaanad filanany iyo fallaari waa kaa fajiciyaan",
"waxaanad heli karayn waxaanad u baahnayn baa laga dhigaa",
"waxay ili aragto ayaa ilko gooyaan",
"weel waliba wixii ku jiruu dhididaa",
"weylasha biree dibigu ha ku quustee",
"Wiil intuu ood ka booduu talo ka boodaa",
"wiilkii is waalaba wiil waabiyaa hela",
"wixii faq lagu sheego fagaaray tagaan",
"xaasidaw xoogga beel",
"Xabaallo waalid baa xoolo lagala baxaa",
"xadhko geel ma wada xidhaan",
"Xaglo laaban xoolo kuma yimaadaan",
"Xalaafo waa Xoogii Xirsi Muude",
"Xarrago dumar xanuun ma leh",
"Xiiso iyo xoorba way gudhaan",
"Xog mooge xaajo waa dilaa",
"Xoolo lama cunee dadkoodaa la cunaa",
"Xoolo quudheed waa la qaataa, soor quudheedse lama qaato",
"Xoorkii laga dhamay xagaagii iyo xusuus baa geel lagu xer geeyaa",
"Xornimo adaa ku noole, iyadu kuguma noola",







    

]
